In [111]:
import torch

In [112]:
scalar = torch.tensor(7)

In [113]:
scalar.item()

7

In [114]:
vector = torch.tensor([1, 3])
vector

tensor([1, 3])

In [115]:
vector.ndim

1

In [116]:
vector.shape

torch.Size([2])

In [117]:
MATRIX = torch.tensor([[1,2], [3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [118]:
MATRIX.ndim

2

In [119]:
MATRIX.shape

torch.Size([2, 2])

In [120]:
TENSOR = torch.tensor([[[1,2], [3,4], [5,6]]])
TENSOR

tensor([[[1, 2],
         [3, 4],
         [5, 6]]])

In [121]:
TENSOR.ndim    

3

In [122]:
TENSOR.shape

torch.Size([1, 3, 2])

In [123]:
TENSOR[0]

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [124]:
TENSOR.ndim

3

In [125]:
random_tensor = torch.randn(2, 3, 2)
random_tensor

tensor([[[-0.2852,  1.5519],
         [-0.2052, -0.3374],
         [-1.7672, -1.1949]],

        [[ 0.5693,  0.1509],
         [ 0.3589, -0.1030],
         [-1.3600, -0.4351]]])

In [126]:
random_tensor.shape

torch.Size([2, 3, 2])

In [127]:
random_tensor.size(), random_tensor.ndim

(torch.Size([2, 3, 2]), 3)

In [128]:
zeros = torch.zeros(2, 3, 2)
ones = torch.ones(2, 1)
zeros, ones

(tensor([[[0., 0.],
          [0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.],
          [0., 0.]]]),
 tensor([[1.],
         [1.]]))

In [129]:
zeros * random_tensor

tensor([[[-0., 0.],
         [-0., -0.],
         [-0., -0.]],

        [[0., 0.],
         [0., -0.],
         [-0., -0.]]])

In [130]:
torch.arange(11, 15)[2]

tensor(13)

In [131]:
torch.__version__

'2.7.1+cpu'

In [132]:
torch.Tensor(1), torch.tensor(1)

(tensor([6.8570e-41]), tensor(1))

In [133]:
import numpy as np

In [134]:
array = np.array([1.0, 10.0])
tensor_torch = torch.tensor([1, 10])
tensor = torch.from_numpy(array)
array, tensor_torch, tensor

(array([ 1., 10.]), tensor([ 1, 10]), tensor([ 1., 10.], dtype=torch.float64))

In [135]:
array.dtype, tensor.dtype, tensor_torch.dtype

(dtype('float64'), torch.float64, torch.int64)

In [136]:
tensor_torch.numpy().dtype, tensor_torch.dtype

(dtype('int64'), torch.int64)

In [138]:
np.linspace(-math.pi, math.pi, 6)

NameError: name 'math' is not defined

In [139]:
torch.manual_seed(42)
torch.rand(2, 2, 3)

tensor([[[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009]],

        [[0.2566, 0.7936, 0.9408],
         [0.1332, 0.9346, 0.5936]]])

In [140]:
torch.rand(2, 2, 3).ndim

3

In [141]:
torch.rand(2,2,3)

tensor([[[0.1053, 0.2695, 0.3588],
         [0.1994, 0.5472, 0.0062]],

        [[0.9516, 0.0753, 0.8860],
         [0.5832, 0.3376, 0.8090]]])

In [142]:
device = "cpu" if not torch.cuda.is_available() else "cpu"
device

'cpu'

In [143]:
tensor, tensor.device

(tensor([ 1., 10.], dtype=torch.float64), device(type='cpu'))

In [144]:
t = torch.rand(4, 2)
print(t)

tensor([[0.5779, 0.9040],
        [0.5547, 0.3423],
        [0.6343, 0.3644],
        [0.7104, 0.9464]])


In [145]:
torch.abs(t), torch.asin(t)

(tensor([[0.5779, 0.9040],
         [0.5547, 0.3423],
         [0.6343, 0.3644],
         [0.7104, 0.9464]]),
 tensor([[0.6162, 1.1290],
         [0.5880, 0.3494],
         [0.6872, 0.3730],
         [0.7901, 1.2419]]))

In [146]:
x = torch.tensor([1,2,3]).unsqueeze(dim=-2)
y = torch.tensor([[1,2], [3,4], [5,6]])
print(f"X dimensions: {x.dim()}, Y dimensions: {y.ndim}")
print(f"X shape: {x.shape}, Y shape: {y.shape}")

X dimensions: 2, Y dimensions: 2
X shape: torch.Size([1, 3]), Y shape: torch.Size([3, 2])


*inner dimensions must match*
## works: (2,3) * (3,2)
## wont work: (3,2) * (3,2)
*resulting shape is the outer dimension multiplied*

In [147]:
torch.matmul(x, y)

tensor([[22, 28]])

In [148]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[1,2],
                         [4,5],
                         [7,8]])
print(f"Tensor A shape: {tensor_A.shape}, Tensor B shape: {tensor_B.shape}")
print(f"Tensor A dimensions: {tensor_A.dim()}, Tensor B dimensions: {tensor_B.dim()}")
print(f"Tensor A: {tensor_A}, Tensor B: {tensor_B}")


Tensor A shape: torch.Size([3, 2]), Tensor B shape: torch.Size([3, 2])
Tensor A dimensions: 2, Tensor B dimensions: 2
Tensor A: tensor([[1, 2],
        [3, 4],
        [5, 6]]), Tensor B: tensor([[1, 2],
        [4, 5],
        [7, 8]])


In [149]:
torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_A.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [ ]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 5, 14, 23],
        [11, 32, 53],
        [17, 50, 83]])

In [ ]:
tensor_A, torch.min(tensor_A), tensor_A.min()

(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 tensor(1),
 tensor(1))

In [ ]:
torch.mean(tensor_A.float())

tensor(3.5000)

In [ ]:
torch.sum(tensor_A)

tensor(21)

In [ ]:
print((tensor_A == torch.max(tensor_A)).nonzero().squeeze())

tensor([2, 1])


In [ ]:
torch.argmax(tensor_A)

tensor(5)

In [ ]:
tensor_A[2][1]

tensor(6)

In [ ]:
tensor_A.shape

torch.Size([3, 2])

In [ ]:
tensor_A.reshape(2,3,1)

tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]]])

In [150]:
tensor_A_view = tensor_A.view(6,1)
tensor_A_view = 99
tensor_A_view

99

In [ ]:
tensor_A

tensor([[99, 99],
        [99, 99],
        [99, 99]])

In [151]:
x = torch.tensor([1,2,3])
print(x)

tensor([1, 2, 3])


In [165]:
x_view = x.view(3,1)

In [166]:
x is x.view(3,1)

False

In [167]:
x_view[0][0] = 99.
x_view, x

(tensor([[99],
         [ 2],
         [ 3]]),
 tensor([99,  2,  3]))

In [168]:
x.size()

torch.Size([3])

In [172]:
x_reshape = x.reshape(3,1)
x_reshape

tensor([[99],
        [ 2],
        [ 3]])

In [173]:
x.squeeze(dim=0)

tensor([99,  2,  3])

In [201]:
x

tensor([[[0.0050, 0.3068, 0.1165]],

        [[0.9103, 0.6440, 0.7071]]])

In [186]:
x.size()

torch.Size([3])

In [190]:
TENSOR

tensor([[[1, 2],
         [3, 4],
         [5, 6]]])

In [196]:
x = torch.rand(2,1,3)
print(x)

tensor([[[0.0050, 0.3068, 0.1165]],

        [[0.9103, 0.6440, 0.7071]]])


In [200]:
x.permute(2,1,0)

tensor([[[0.0050, 0.9103]],

        [[0.3068, 0.6440]],

        [[0.1165, 0.7071]]])

In [204]:
x = torch.tensor([1,2,3])
x

tensor([1, 2, 3])

In [209]:
x.permute(0)


tensor([1, 2, 3])

In [211]:
t = torch.arange(1, 10).reshape(1,3,3)
t

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [216]:
t.permute(2,0,1)

tensor([[[1, 4, 7]],

        [[2, 5, 8]],

        [[3, 6, 9]]])

In [217]:
t

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [218]:
t[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [219]:
t[0][0]

tensor([1, 2, 3])

In [220]:
t[0][0][0]

tensor(1)

In [222]:
t.dim()

3

In [223]:
t.size()

torch.Size([1, 3, 3])

In [224]:
t.shape

torch.Size([1, 3, 3])

In [231]:
t.shape == t.size()

True

In [232]:
t

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [237]:
t[:,1,1]

tensor([5])

In [239]:
t[0][1][1]

tensor(5)

In [240]:
t[0][2][2]

tensor(9)